name: Build Android Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v0.1.0'
        type: string
      update_detail:
        description: 'Update detail'
        required: false
        default: ''
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 9477386
        accept-android-sdk-licenses: true
        packages: "platform-tools platforms;android-34 build-tools;34.0.0 ndk;25.2.9519653 cmake;3.22.1"

    - name: Install dependencies
      run: npm ci

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli@latest

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          src-tauri/gen/android/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Android environment
      run: |
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
        
    - name: Verify build environment
      run: |
        echo "Verifying Android SDK tools..."
        ls -la $ANDROID_SDK_ROOT/build-tools/34.0.0/
        $ANDROID_SDK_ROOT/build-tools/34.0.0/aapt version
        $ANDROID_SDK_ROOT/build-tools/34.0.0/zipalign
        echo "Java version:"
        java -version
        echo "Environment variables:"
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "NDK_HOME: $NDK_HOME"

    - name: Build Android APK
      run: |
        cd src-tauri
        npx tauri android init
        npx tauri android build --apk

    - name: Sign and align APK
      run: |
        # Decode keystore
        echo "${{ vars.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

        # Find APK
        APK_PATH=$(find src-tauri/gen/android -name "*.apk" -type f | head -1)
        echo "Found APK: $APK_PATH"
        
        # Verify APK exists
        if [ ! -f "$APK_PATH" ]; then
          echo "Error: APK file not found!"
          exit 1
        fi
        
        # First align the APK
        ALIGNED_APK="${APK_PATH%.apk}-aligned.apk"
        $ANDROID_SDK_ROOT/build-tools/34.0.0/zipalign -v 4 "$APK_PATH" "$ALIGNED_APK"
        
        # Then sign the aligned APK using apksigner with v1+v2+v3 signature schemes
        SIGNED_APK="${APK_PATH%.apk}-signed.apk"
        $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner sign \
          --ks keystore.jks \
          --ks-pass pass:"${{ vars.ANDROID_KEYSTORE_PASSWORD }}" \
          --key-pass pass:"${{ vars.ANDROID_KEY_PASSWORD }}" \
          --ks-key-alias "${{ vars.ANDROID_KEY_ALIAS }}" \
          --v1-signing-enabled true \
          --v2-signing-enabled true \
          --v3-signing-enabled true \
          --out "$SIGNED_APK" \
          "$ALIGNED_APK"
        
        # Verify the signature
        $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify "$SIGNED_APK"
        
        # Replace original APK with signed version
        mv "$SIGNED_APK" "$APK_PATH"
        
        # Clean up temporary files
        rm -f keystore.jks "$ALIGNED_APK"
        
        echo "APK signed and verified successfully"

    - name: Find and verify APK files
      id: find-apk
      run: |
        APK_PATH=$(find src-tauri/gen/android -name "*.apk" -type f | head -1)
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "apk_name=$(basename $APK_PATH)" >> $GITHUB_OUTPUT
        
        # Verify APK integrity
        echo "Verifying APK integrity..."
        $ANDROID_SDK_ROOT/build-tools/34.0.0/aapt dump badging "$APK_PATH" | head -5
        
        # Check APK signature schemes
        echo "Checking APK signature schemes..."
        $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify --verbose --print-certs "$APK_PATH"
        
        # Verify specific signature schemes
        echo "Verifying v1 signature..."
        $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify --v1-only "$APK_PATH" && echo "✓ v1 signature valid" || echo "✗ v1 signature invalid"
        echo "Verifying v2 signature..."
        $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify --v2-only "$APK_PATH" && echo "✓ v2 signature valid" || echo "✗ v2 signature invalid"
        echo "Verifying v3 signature..."
        $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify --v3-only "$APK_PATH" && echo "✓ v3 signature valid" || echo "✗ v3 signature invalid"
        
        # Show APK size
        echo "APK size: $(du -h "$APK_PATH" | cut -f1)"

    - name: Rename APK file
      id: rename-apk
      run: |
        OLD_APK_PATH="${{ steps.find-apk.outputs.apk_path }}"
        NEW_APK_NAME="delin-${{ github.event.inputs.version }}-android.apk"
        NEW_APK_PATH="$(dirname $OLD_APK_PATH)/$NEW_APK_NAME"
        mv "$OLD_APK_PATH" "$NEW_APK_PATH"
        echo "renamed_apk_path=$NEW_APK_PATH" >> $GITHUB_OUTPUT
        echo "renamed_apk_name=$NEW_APK_NAME" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.version }}
        body: |
          ## Update detail
          ${{ github.event.inputs.update_detail }}
        files: |
          ${{ steps.rename-apk.outputs.renamed_apk_path }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Summary
      run: |
        echo "## 构建完成 ✅" >> $GITHUB_STEP_SUMMARY
        echo "**版本:** ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "**APK:** ${{ steps.rename-apk.outputs.renamed_apk_name }}" >> $GITHUB_STEP_SUMMARY