name: Build and Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      body: ${{ steps.extract_version.outputs.body }}
      should_release: ${{ steps.check_tag.outputs.exists == 'false' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract latest version from CHANGELOG
        id: extract_version
        run: |
          # 读取CHANGELOG内容
          content=$(cat CHANGELOG.md)

          # 提取最新版本号（第一个##后面的内容）
          version=$(echo "$content" | grep -m 1 '^## ' | sed 's/## //')

          # 提取该版本的内容（直到下一个##或文件结束）
          body=$(echo "$content" | awk -v version="$version" '
            BEGIN { capture = 0 }
            $0 ~ "^## " version { capture = 1; next }
            capture == 1 && $0 ~ "^## " { exit }
            capture == 1 { print }
          ')

          # 输出变量供后续步骤使用
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git rev-parse "${{ steps.extract_version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  build-windows-x64:
    needs: prepare-release
    if: needs.prepare-release.outputs.should_release == 'true'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\cargo\bin\
            ~\AppData\Local\cargo\registry\index\
            ~\AppData\Local\cargo\registry\cache\
            ~\AppData\Local\cargo\git\db\
            src-tauri\target\
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc

      - name: Install prerequisites
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build Windows installer
        run: |
          npm run tauri build

      - name: Rename installer
        id: rename-installer
        shell: pwsh
        run: |
          $INSTALLER_PATH = Get-ChildItem -Path "src-tauri\target\release\bundle\nsis\*.exe" | Select-Object -First 1
          $NEW_NAME = "Delin-${{ needs.prepare-release.outputs.version }}-windows-x64-setup.exe"
          $NEW_PATH = Join-Path (Split-Path $INSTALLER_PATH) $NEW_NAME
          Move-Item -Path $INSTALLER_PATH -Destination $NEW_PATH
          echo "installer_path=$NEW_PATH" >> $env:GITHUB_OUTPUT
          echo "installer_name=$NEW_NAME" >> $env:GITHUB_OUTPUT

      - name: Upload Windows installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: ${{ steps.rename-installer.outputs.installer_path }}
          if-no-files-found: error

  build-macos:
    needs: prepare-release
    if: needs.prepare-release.outputs.should_release == 'true'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Install dependencies
        run: npm ci

      - name: Build macOS app
        run: |
          npm run tauri build

      - name: Find and rename DMG file
        id: rename-dmg
        run: |
          DMG_PATH=$(find src-tauri/target/release/bundle/dmg -name "*.dmg" -type f | head -1)
          NEW_NAME="Delin-${{ needs.prepare-release.outputs.version }}-macos.dmg"
          NEW_PATH="$(dirname $DMG_PATH)/$NEW_NAME"
          mv "$DMG_PATH" "$NEW_PATH"
          echo "dmg_path=$NEW_PATH" >> $GITHUB_OUTPUT
          echo "dmg_name=$NEW_NAME" >> $GITHUB_OUTPUT

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: ${{ steps.rename-dmg.outputs.dmg_path }}
          if-no-files-found: error

  build-android:
    needs: prepare-release
    if: needs.prepare-release.outputs.should_release == 'true'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 9477386
        accept-android-sdk-licenses: true
        packages: "platform-tools platforms;android-34 build-tools;34.0.0 ndk;25.2.9519653 cmake;3.22.1"

    - name: Install dependencies
      run: npm ci

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          src-tauri/gen/android/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Android environment
      run: |
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

    - name: Build Android APK
      run: |
        cd src-tauri
        npx tauri android init
        npx tauri android build --apk

    - name: Sign APK
      run: |
        # Decode keystore
        echo "${{ vars.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

        # Find and sign APK (apksigner handles alignment automatically)
        APK_PATH=$(find src-tauri/gen/android -name "*.apk" -type f | head -1)
        $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner sign \
          --ks keystore.jks \
          --ks-pass pass:"${{ vars.ANDROID_KEYSTORE_PASSWORD }}" \
          --ks-key-alias "${{ vars.ANDROID_KEY_ALIAS }}" \
          --key-pass pass:"${{ vars.ANDROID_KEY_PASSWORD }}" \
          "$APK_PATH"

        # Clean up
        rm -f keystore.jks

    - name: Find APK files
      id: find-apk
      run: |
        APK_PATH=$(find src-tauri/gen/android -name "*.apk" -type f | head -1)
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "apk_name=$(basename $APK_PATH)" >> $GITHUB_OUTPUT

    - name: Rename APK file
      id: rename-apk
      run: |
        OLD_APK_PATH="${{ steps.find-apk.outputs.apk_path }}"
        NEW_APK_NAME="Delin-${{ needs.prepare-release.outputs.version }}-android.apk"
        NEW_APK_PATH="$(dirname $OLD_APK_PATH)/$NEW_APK_NAME"
        mv "$OLD_APK_PATH" "$NEW_APK_PATH"
        echo "renamed_apk_path=$NEW_APK_PATH" >> $GITHUB_OUTPUT
        echo "renamed_apk_name=$NEW_APK_NAME" >> $GITHUB_OUTPUT

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-release
        path: ${{ steps.rename-apk.outputs.renamed_apk_path }}
        if-no-files-found: error

  create-release:
    needs: [prepare-release, build-android, build-windows-x64, build-macos]
    if: needs.prepare-release.outputs.should_release == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare-release.outputs.version }}
          name: ${{ needs.prepare-release.outputs.version }}
          body: ${{ needs.prepare-release.outputs.body }}
          files: |
            artifacts/android-release/*
            artifacts/windows-installer/*
            artifacts/macos-release/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
