name: Release from Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Read changelog
        id: changelog
        run: |
          # 提取最新版本号和内容
          latest=$(awk '/^# v[0-9]+\.[0-9]+\.[0-9]+/ {print $2; exit}' changelog.md)
          if [ -z "$latest" ]; then
            echo "No version found"
            exit 1
          fi

          # 检查 tag 是否已存在
          if git rev-parse "refs/tags/$latest" >/dev/null 2>&1; then
            echo "Tag $latest already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # 提取该版本下的更新内容
          body=$(awk -v ver="$latest" '
            $0 ~ ("# " ver) {flag=1; next}
            /^#/ {flag=0}
            flag {print}
          ' changelog.md)

          echo "version=$latest" >> $GITHUB_OUTPUT
          echo "body=$body" >> $GITHUB_OUTPUT
          echo "exists=false" >> $GITHUB_OUTPUT

      - name: Create Release
        if: steps.changelog.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          name: ${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
