name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.1.1)'
        required: true
        default: 'v0.1.1'
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract release notes
      id: extract_release_notes
      uses: ffurrer2/extract-release-notes@v2
      with:
        changelog_file: CHANGELOG.md
        version: ${{ github.event.inputs.version }}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.version }}
        body: ${{ steps.extract_release_notes.outputs.release_notes }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}