name: Build Windows Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v0.1.0'
        type: string
      update_detail:
        description: 'Update detail'
        required: false
        default: ''
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Install dependencies
      run: npm ci

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli@latest

    - name: Build Windows executable
      run: |
        cd src-tauri
        npx tauri build --target x86_64-pc-windows-msvc

    - name: Find executable files
      id: find-exe
      run: |
        $EXE_PATH = Get-ChildItem -Path "src-tauri\target\x86_64-pc-windows-msvc\release" -Name "*.exe" | Where-Object { $_ -notlike "*deps*" -and $_ -notlike "*build*" } | Select-Object -First 1
        $FULL_EXE_PATH = "src-tauri\target\x86_64-pc-windows-msvc\release\$EXE_PATH"
        echo "exe_path=$FULL_EXE_PATH" >> $env:GITHUB_OUTPUT
        echo "exe_name=$EXE_PATH" >> $env:GITHUB_OUTPUT

    - name: Rename executable file
      id: rename-exe
      run: |
        $OLD_EXE_PATH = "${{ steps.find-exe.outputs.exe_path }}"
        $NEW_EXE_NAME = "delin-${{ github.event.inputs.version }}-windows.exe"
        $NEW_EXE_PATH = "$(Split-Path $OLD_EXE_PATH)\$NEW_EXE_NAME"
        Move-Item -Path $OLD_EXE_PATH -Destination $NEW_EXE_PATH
        echo "renamed_exe_path=$NEW_EXE_PATH" >> $env:GITHUB_OUTPUT
        echo "renamed_exe_name=$NEW_EXE_NAME" >> $env:GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.version }}
        body: |
          ## Update detail
          ${{ github.event.inputs.update_detail }}
        files: |
          ${{ steps.rename-exe.outputs.renamed_exe_path }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Summary
      run: |
        echo "## 构建完成 ✅" >> $env:GITHUB_STEP_SUMMARY
        echo "**版本:** ${{ github.event.inputs.version }}" >> $env:GITHUB_STEP_SUMMARY
        echo "**可执行文件:** ${{ steps.rename-exe.outputs.renamed_exe_name }}" >> $env:GITHUB_STEP_SUMMARY